version: '2'

services:
  nginx:
    build: ./nginx
    networks:
      - back
    ports:
      - "80:80"

  db:
    build: ./db
    networks:
      - back
    environment:
      MYSQL_ROOT_PASSWORD: testing
      MYSQL_USER: bryggeriklubben
      MYSQL_PASSWORD: BryggeriKlubben
  #  volumes:
  #    - ./db:/docker-entrypoint-initdb.d

  #client:
   # build: ./client

  api_get:
    build: ./api
    networks:
      - back
    links:
      - db:db
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://bryggeriklubben:BryggeriKlubben@db/inventory
  api_post:
    build: ./api
    networks:
      - back
    links:
      - db:db
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://bryggeriklubben:BryggeriKlubben@db/inventory

  api_put:
    build: ./api
    networks:
      - back
    links:
      - db:db
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://bryggeriklubben:BryggeriKlubben@db/inventory

  api_delete:
    build: ./api
    networks:
      - back
    links:
      - db:db
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://bryggeriklubben:BryggeriKlubben@db/inventory

networks:
  back:

