nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
   - api:api
   - db:db
db:
  build: ./db
  environment:
    MYSQL_ROOT_PASSWORD: testing
    MYSQL_USER: bryggeriklubben
    MYSQL_PASSWORD: BryggeriKlubben
#  volumes:
#    - ./db:/docker-entrypoint-initdb.d

client:
  build: ./client

api:
  build: ./api
  ports:
    - "5000:5000"
  links:
    - db:db