version: '2'

services:
  nginx:
    build: ./nginx
    networks:
      - back
    ports:
      - "80:80"
    links:
     - api:api
  db:
    build: ./db
    networks:
      - back
    environment:
      MYSQL_ROOT_PASSWORD: testing
      MYSQL_USER: bryggeriklubben
      MYSQL_PASSWORD: BryggeriKlubben
  #  volumes:
  #    - ./db:/docker-entrypoint-initdb.d

  #client:
   # build: ./client

  api:
    build: ./api
    networks:
      - back
    ports:
      - "5000:5000"
    links:
      - db:db
networks:
  back:

